package com.wayapay.ng.landingpage.models

import com.wayapaychat.core.wayagram.Poll
import com.wayapaychat.core.wayagram.Vote
import com.wayapaychat.local.room.models.WayaGramUser
import java.io.Serializable

data class WayaInterest(
        var id: String = "",
        var interest: String = "",
):Serializable

data class WayaGroup(
    var id:String = "",
    var ownerId:String = "",
    var groupName:String? = null,
    var description: String? = null,
    var profileImageUri: String = "",
    var headerImageUri: String = "",
    var isPublic: Boolean = true,
    var profileImagePath:String = "",
    var headerImagePath:String = "",
    var imageUrl:String = "",
    var headerUrl:String = "",
    var username :String? = null,
    var muted: Boolean = false,
    var isDeleted: Boolean = false,
    var createdAt: String = "",
    var updatedAt: String = "",
):Serializable

data class WayaPages(
    var pageId:String = "",
    var ownerId:String = "",
    var pageName:String? = null,
    var pageCategory: String? = null,
    var categoryId: String = "",
    var description: String? = null,
    var profileImageUri: String = "",
    var headerImageUri: String = "",
    var websiteUrl:String? = null,
    var isPublic: Boolean = true,
    var profileImagePath:String = "",
    var headerImagePath:String = "",
    var imageUrl:String = "",
    var headerUrl:String = "",
    var username :String? = null,
    var createdAt: String = "",
    var updatedAt: String = "",
    var followers: Long = 0,
    var likes: Long = 0,
    var isFollowing: Boolean = false,
    var hasLiked: Boolean = false
):Serializable

data class WayaPost(
    var id: String = "",
    var profileId: String = "",
    var avatar: String = "",
    var firstName: String = "",
    var surname: String = "",
    var displayName: String = "$firstName $surname",
    var authUserId: String = "",
    var gramUserId: String = "",
    var likes: Long = 0,
    var isLiked: Boolean = false,
    var commentCount: Long = 0,
    var repostCont: Long = 0,
    var parent_id: String? = null,
    var group_id: String? = null,
    var pageId: String? = null,
    var userId: String? = null,
    var type: String? = null,
    var serverType: String = PostType.USER,
    var text: String? = null,
    var hashtags:List<String> = emptyList(),
    var mentions:List<String> = emptyList(),
    var userDisplayName: String? = null,
    var username: String? = null,
    var userEmail: String? = null,
    var userPhoneNumber: String? = null,
    var createdAt: String = "",
    var updatedAt: String = "",
    var listOptions: List<String> = listOf(),
    var listVotes: MutableList<Vote> = mutableListOf(),
    var listImageUri: MutableList<String> = mutableListOf(),
    var listImageUrl: List<String> = listOf(),
    var listAbsolutePath: MutableList<String> = mutableListOf(),
    var poolLength: Long = 0,
    var poolEndTime: Long = System.currentTimeMillis(),
    var isPoolPaid: Boolean = false,
    var price: Double = 0.0,
    var isPoll: Boolean = false,
    var postType: String = PostType.VOTE,
    val isDeleted: Boolean = false,
    var voteLimit: Int = 1,
    val user: WayaGramUser = WayaGramUser(),
    var poll: Poll = Poll(),
):Serializable

data class WayaEvent(
    var id:String = "",
    var title: String = "",
    var creatorId: String = "",
    var creatorNumber: String = "",
    var creatorEmail: String = "",
    var organizer: String = "",
    var eventTags: List<String> = mutableListOf(),
    var private: Boolean = false,
    var virtual: Boolean = false,
    var eventLocation: String = "",
    var urlLink:String = "",
    var filePath:String = "",
    var startTime:Long = System.currentTimeMillis(),
    var endTime: Long = System.currentTimeMillis(),
    var freeToAttend: Boolean = false,
    var fee: Double = 0.00,
    var registeredCount: Int = 0,
    var interested: Int = 0,
    var going: Int = 0,
    var eventImageUrl:String = "",
    var eventImageUri:String = "",
    var tag: String = "",
    var isOwner: Boolean = false,
):Serializable